name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 */12 * * *'
    # scheduled for 00:00 every Monday

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: The-Forbidden-Trove/character_name_blacklist      # set the upstream repo
          upstream-branch: main   # set the upstream branch to merge from
          branch: main          # set the branch to merge to
